PRINT "HELLO "; REM A SIMPLE WORDS DISPLAY COMMAND
PRINT "I AM BACK TO THE WORLD OF PROAGRAMMING"
PRINT " AND I MUST TELL YOU, THAT BY HOOK OR CROOK I WILL WIN"
PRINT " YES I WAS LIKE A MISGUIDED MISSILE..."
PRINT " YES I DRPPED THE BALL...";
PRINT "I.E., I LET A WHOLE YEAR GO BY WHILE I DID NOTHING"
PRINT "AND I REGRET THIS...";
PRINT " WHAT MORE CAN I DO..."
PRINT " BUT I MUST FIGHT NOW, ";
PRINT "AND FORGETTING ABOUT PAIN AND LEARNING FROM MY MISTAKE I MUST FIGHT BACK"
PRINT "THAT'S IT FOLKS!!!"
